// ============================================================
// Ports Dataset
// Source: UN/LOCODE (free public data) + trade.gov
// Phase 2: Data Foundation
// ============================================================

import type { Port, CountryCode } from "@/lib/types";

export const PORTS: Port[] = [
  // ─── US West Coast ──────────────────────────────────────
  {
    unlocode: "USLAX",
    name: "Port of Los Angeles",
    city: "Los Angeles",
    country: "US",
    lat: 33.7395,
    lng: -118.2659,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Los Angeles FTZ #202",
    congestionLevel: "high",
    avgDwellDays: 3.2,
    demurrageRate: 300,
    detentionRate: 150,
    freeDays: 4,
  },
  {
    unlocode: "USLGB",
    name: "Port of Long Beach",
    city: "Long Beach",
    country: "US",
    lat: 33.7543,
    lng: -118.2162,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Long Beach FTZ #50",
    congestionLevel: "high",
    avgDwellDays: 3.5,
    demurrageRate: 300,
    detentionRate: 150,
    freeDays: 4,
  },
  {
    unlocode: "USSEA",
    name: "Port of Seattle/Tacoma (NWSA)",
    city: "Seattle",
    country: "US",
    lat: 47.5615,
    lng: -122.3378,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Seattle FTZ #5",
    congestionLevel: "medium",
    avgDwellDays: 2.8,
    demurrageRate: 250,
    detentionRate: 125,
    freeDays: 5,
  },
  // ─── US East Coast ──────────────────────────────────────
  {
    unlocode: "USNYC",
    name: "Port of New York/New Jersey",
    city: "New York",
    country: "US",
    lat: 40.6635,
    lng: -74.0636,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "New York FTZ #1",
    congestionLevel: "medium",
    avgDwellDays: 3.0,
    demurrageRate: 350,
    detentionRate: 175,
    freeDays: 4,
  },
  {
    unlocode: "USSAV",
    name: "Port of Savannah",
    city: "Savannah",
    country: "US",
    lat: 32.0835,
    lng: -81.0998,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Savannah FTZ #104",
    congestionLevel: "medium",
    avgDwellDays: 2.5,
    demurrageRate: 225,
    detentionRate: 110,
    freeDays: 5,
  },
  {
    unlocode: "USHOU",
    name: "Port of Houston",
    city: "Houston",
    country: "US",
    lat: 29.7272,
    lng: -95.0278,
    type: "seaport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Houston FTZ #84",
    congestionLevel: "low",
    avgDwellDays: 2.2,
    demurrageRate: 200,
    detentionRate: 100,
    freeDays: 6,
  },
  // ─── China ──────────────────────────────────────────────
  {
    unlocode: "CNSHA",
    name: "Port of Shanghai",
    city: "Shanghai",
    country: "CN",
    lat: 31.3497,
    lng: 121.5213,
    type: "seaport",
    role: "origin",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Shanghai Free Trade Zone",
    congestionLevel: "medium",
    avgDwellDays: 1.5,
    demurrageRate: 200,
    detentionRate: 100,
    freeDays: 7,
  },
  {
    unlocode: "CNSHE",
    name: "Port of Shenzhen (Yantian)",
    city: "Shenzhen",
    country: "CN",
    lat: 22.5593,
    lng: 114.2683,
    type: "seaport",
    role: "origin",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "medium",
    avgDwellDays: 1.8,
    demurrageRate: 180,
    detentionRate: 90,
    freeDays: 7,
  },
  {
    unlocode: "CNGGZ",
    name: "Port of Guangzhou (Nansha)",
    city: "Guangzhou",
    country: "CN",
    lat: 22.7614,
    lng: 113.5886,
    type: "seaport",
    role: "origin",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Nansha FTZ",
    congestionLevel: "medium",
    avgDwellDays: 2.0,
    demurrageRate: 180,
    detentionRate: 90,
    freeDays: 7,
  },
  {
    unlocode: "CNNBO",
    name: "Port of Ningbo-Zhoushan",
    city: "Ningbo",
    country: "CN",
    lat: 29.8683,
    lng: 121.6538,
    type: "seaport",
    role: "origin",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "low",
    avgDwellDays: 1.5,
    demurrageRate: 160,
    detentionRate: 80,
    freeDays: 7,
  },
  // ─── Vietnam ────────────────────────────────────────────
  {
    unlocode: "VNHPH",
    name: "Port of Haiphong",
    city: "Haiphong",
    country: "VN",
    lat: 20.8597,
    lng: 106.6881,
    type: "seaport",
    role: "origin",
    tier: 2,
    coldChainCapable: false,
    ftzNearby: false,
    congestionLevel: "medium",
    avgDwellDays: 3.0,
    demurrageRate: 120,
    detentionRate: 60,
    freeDays: 5,
  },
  {
    unlocode: "VNSGN",
    name: "Tan Cang-Cat Lai Terminal (Ho Chi Minh City)",
    city: "Ho Chi Minh City",
    country: "VN",
    lat: 10.7626,
    lng: 106.7533,
    type: "seaport",
    role: "origin",
    tier: 2,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "medium",
    avgDwellDays: 2.5,
    demurrageRate: 130,
    detentionRate: 65,
    freeDays: 5,
  },
  // ─── Thailand ───────────────────────────────────────────
  {
    unlocode: "THBKK",
    name: "Laem Chabang Port",
    city: "Laem Chabang",
    country: "TH",
    lat: 13.0844,
    lng: 100.8881,
    type: "seaport",
    role: "origin",
    tier: 2,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "low",
    avgDwellDays: 2.0,
    demurrageRate: 110,
    detentionRate: 55,
    freeDays: 7,
  },
  // ─── Indonesia ──────────────────────────────────────────
  {
    unlocode: "IDJKT",
    name: "Tanjung Priok Port",
    city: "Jakarta",
    country: "ID",
    lat: -6.1046,
    lng: 106.8804,
    type: "seaport",
    role: "origin",
    tier: 2,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "medium",
    avgDwellDays: 3.5,
    demurrageRate: 100,
    detentionRate: 50,
    freeDays: 5,
  },
  // ─── Singapore (Transshipment Hub) ──────────────────────
  {
    unlocode: "SGSIN",
    name: "Port of Singapore (PSA)",
    city: "Singapore",
    country: "MY",  // region code
    lat: 1.2655,
    lng: 103.8215,
    type: "seaport",
    role: "transshipment",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: false,
    congestionLevel: "low",
    avgDwellDays: 1.0,
    demurrageRate: 250,
    detentionRate: 125,
    freeDays: 7,
  },
  // ─── Malaysia ───────────────────────────────────────────
  {
    unlocode: "MYPKG",
    name: "Port Klang",
    city: "Port Klang",
    country: "MY",
    lat: 3.0083,
    lng: 101.3697,
    type: "seaport",
    role: "both",
    tier: 2,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Port Klang FTZ",
    congestionLevel: "low",
    avgDwellDays: 2.0,
    demurrageRate: 130,
    detentionRate: 65,
    freeDays: 7,
  },
  // ─── Cambodia ───────────────────────────────────────────
  {
    unlocode: "KHPNH",
    name: "Sihanoukville Autonomous Port",
    city: "Preah Sihanouk",
    country: "KH",
    lat: 10.6167,
    lng: 103.5167,
    type: "seaport",
    role: "origin",
    tier: 3,
    coldChainCapable: false,
    ftzNearby: false,
    congestionLevel: "low",
    avgDwellDays: 4.0,
    demurrageRate: 80,
    detentionRate: 40,
    freeDays: 5,
  },
  // ─── US Airports ────────────────────────────────────────
  {
    unlocode: "USLAX-AIR",
    name: "Los Angeles International Airport (LAX)",
    city: "Los Angeles",
    country: "US",
    lat: 33.9425,
    lng: -118.4081,
    type: "airport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "LAX FTZ #202",
    congestionLevel: "medium",
    avgDwellDays: 0.5,
    demurrageRate: 400,
    detentionRate: 200,
    freeDays: 2,
  },
  {
    unlocode: "USJFK-AIR",
    name: "John F. Kennedy International Airport (JFK)",
    city: "New York",
    country: "US",
    lat: 40.6413,
    lng: -73.7781,
    type: "airport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "JFK Airport FTZ #17",
    congestionLevel: "medium",
    avgDwellDays: 0.5,
    demurrageRate: 450,
    detentionRate: 225,
    freeDays: 2,
  },
  {
    unlocode: "USORD-AIR",
    name: "O'Hare International Airport (ORD)",
    city: "Chicago",
    country: "US",
    lat: 41.9742,
    lng: -87.9073,
    type: "airport",
    role: "destination",
    tier: 1,
    coldChainCapable: true,
    ftzNearby: true,
    ftzName: "Chicago FTZ #22",
    congestionLevel: "low",
    avgDwellDays: 0.4,
    demurrageRate: 380,
    detentionRate: 190,
    freeDays: 2,
  },
];

// ─── Lookup Utilities ─────────────────────────────────────

export function getPort(unlocode: string): Port | undefined {
  return PORTS.find((p) => p.unlocode === unlocode);
}

export function getPortsByCountry(country: CountryCode): Port[] {
  return PORTS.filter((p) => p.country === country);
}

export function getOriginPorts(): Port[] {
  return PORTS.filter((p) => p.role === "origin" || p.role === "both");
}

export function getDestinationPorts(): Port[] {
  return PORTS.filter((p) => (p.role === "destination" || p.role === "both") && p.country === "US");
}

export function getTransshipmentPorts(): Port[] {
  return PORTS.filter((p) => p.role === "transshipment");
}

export function searchPorts(query: string): Port[] {
  const q = query.toLowerCase();
  return PORTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.city.toLowerCase().includes(q) ||
      p.unlocode.toLowerCase().includes(q)
  );
}
